# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160312_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
