# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_voyage_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
