# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 15:32
from __future__ import unicode_literals

from django.db import migrations


def calculate_durations(apps, schema_editor):
    Voyage = apps.get_model('main', 'Voyage')
    for voyage in Voyage.objects.all():
        if voyage.time_ended:
            delta = voyage.time_ended - voyage.time_started
            voyage.duration = delta.seconds
            voyage.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_auto_20160423_1732'),
    ]

    operations = [
        migrations.RunPython(calculate_durations, reverse_code=migrations.RunPython.noop)
    ]
